Feature/add marine biodiversity layer
Vizzuality/half-earth-v3 pull request #270
Opened 2021-05-11 14:25 UTC by weberjavi

## Fishes priority & marine mammals layers
### Description
This PR adds the tile layers for _fishes priority_, _marine mammals priority, rarity and richness_, and _marine vertebrates priority, rarity and richness_.
It also adds a documentation page, under the `docs` folder, that explains the steps to follow in order to add new layers to the project.
Some changes to file names have been made.
### Testing instructions
Check the biodiversity sidebar and toggle  marine layers. Make sure the metadata for the layers is there after clicking the info buttons.
Read the `docs` file `layers-update-flow.md`.
### Feature relevant tickets
https://vizzuality.atlassian.net/browse/HE-20

2021-05-11 15:14 UTC, gretacv commented on docs/layers-update-flow.md
> +- The last step for a layer to be ready to be usede on the platform is to add the needed configuration to be consumed by the `legend` component. Diferent legend configuration are created depending on
```suggestion
- The last step for a layer to be ready to be used on the platform is to add the needed configuration to be consumed by the `legend` component. Different legend configurations are created depending on the category of the layer (_biodiversity_, _human pressures_ or _protected areas_), and those are stored into the associated file in the `constants` folder. In this case, fishes priority layer, the legend config to be updated is located on the `constants/biodiversity-layers-constants` file.
```

2021-05-11 15:16 UTC, gretacv commented on src/constants/biodiversity-layers-constants.js
> +    title: "Fishes priority"
```suggestion
    title: "Global fishes priority"
```

2021-05-11 15:17 UTC, gretacv commented on src/constants/biodiversity-layers-constants.js
> +    title: "Marine mammals priority"
```suggestion
    title: "Global marine mammals priority"
```

2021-05-11 15:21 UTC, gretacv commented on src/constants/biodiversity-layers-constants.js
> +          name: 'marine vertebrates',
```suggestion
          name: 'all marine vertebrates',
```

2021-05-11 15:31 UTC, gretacv commented on docs/layers-update-flow.md
> +    ```
```suggestion
    ```
- Once the layer is ready to be used by the platform some changes in the UI are needed. Change the size of the sidebar card in `src/components/biodiversity-sidebar-card/biodiversity-sidebar-card-styles.module.scss` so the new element is visible. To have the opening effect the size of the side bar is provided manually.  
```

2021-05-11 15:44 UTC, gretacv commented on src/constants/biodiversity-layers-constants.js
> +    title: "Global Mammals priority"
```suggestion
    title: "Global Terrestrial Mammals priority"
```

2021-05-11 15:45 UTC, gretacv commented on src/constants/biodiversity-layers-constants.js
> +    title: "Mammals rarity"
```suggestion
    title: "Terrestrial Mammals rarity"
```

2021-05-11 15:45 UTC, gretacv commented on src/constants/biodiversity-layers-constants.js
> +    title: "Mammals richness"
```suggestion
    title: "Terrestrial Mammals richness"
```

2021-05-11 15:46 UTC, gretacv commented on src/constants/biodiversity-layers-constants.js
> +    title: "All groups rarity"
```suggestion
    title: "All terrestrial groups rarity"
```

2021-05-11 15:47 UTC, gretacv commented on src/constants/biodiversity-layers-constants.js
> +    title: "All groups richness"
```suggestion
    title: "All terrestrial groups richness"
```

2021-05-24 07:27 UTC, gretacv requested changes
Javi, the only bit of code that needs change is the name on the legend for the `global marine vertebrates` priority. 
I also updated the metadata for the text `Where to start to protect?`, I am unsure if you have verified the pixel space is correct following design. However, maybe it is not worth checking it as maybe MOL share an updated text that changes the size of the card.

2021-05-24 07:27 UTC, gretacv commented on src/constants/biodiversity-layers-constants.js
> +    title: "Marine vertebrates priority"
```suggestion
    title: "Global marine vertebrates priority"
```

2021-05-24 09:39 UTC, weberjavi commented
@gretacv everything working great :)

Do you approve it?

![image](https://user-images.githubusercontent.com/6906348/119328628-9a939400-bc84-11eb-8309-49a59a47f7b7.png)

2021-05-24 09:55 UTC, weberjavi commented
gonna merge it :D

2021-05-24 09:56 UTC, merged